spring.application.name=MunicipalBack

# Configuración del puerto del servidor
server.port=8080    

# Configuración de la conexión a la base de datos postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/blibMunicipalDB
spring.datasource.username=blibMunicipal
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ⚙️ JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

security.jwt.secret=dSQosb1ps0idw3aRL9pCpG8m2QLHcJENIJv0D6Vbskp
security.jwt.expiration-ms=86400000